In [1]:
# AI Data Insights Generator

## Module 3 - Data Cleaning

### Objective
#Clean and prepare the dataset for analysis by handling missing values, duplicates, incorrect data types, and inconsistent column names.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("SampleSuperstore.csv")

In [4]:
df.head()

,Row ID+O6G3A1:R6,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode,ind1,ind2
0,4918,CA-2019-160304,01-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",73.94,1,28.2668,NaN,Online,NaN,NaN
1,4919,CA-2019-160304,02-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",173.94,3,38.2668,NaN,Online,NaN,NaN
2,4920,CA-2019-160304,02-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Technology,Phones,GE 30522EE2,231.98,2,67.2742,NaN,Cards,NaN,NaN
3,3074,CA-2019-125206,03-01-2019,05-01-2019,First Class,LR-16915,Lena Radford,Consumer,United States,Los Angeles,...,Office Supplies,Storage,Recycled Steel Personal File for Hanging File ...,114.46,2,28.6150,NaN,Online,NaN,NaN
4,8604,US-2019-116365,03-01-2019,08-01-2019,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,...,Technology,Accessories,Imation Clip USB flash drive - 8 GB,30.08,2,-5.2640,NaN,Online,NaN,NaN

In [5]:
df.isnull().sum()

Row ID+O6G3A1:R6       0
Order ID               0
Order Date             0
Ship Date              0
Ship Mode              0
Customer ID            0
Customer Name          0
Segment                0
Country                0
City                   0
State                  0
Region                 0
Product ID             0
Category               0
Sub-Category           0
Product Name           0
Sales                  0
Quantity               0
Profit                 0
Returns             5614
Payment Mode           0
ind1                5901
ind2                5901
dtype: int64

In [6]:
df["Returns"].value_counts(dropna=False)

Returns
NaN    5614
1.0     287
Name: count, dtype: int64

In [7]:
df = df.drop(columns=["ind1", "ind2"])

In [8]:
df.columns

Index(['Row ID+O6G3A1:R6', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales', 'Quantity', 'Profit', 'Returns', 'Payment Mode'],
      dtype='str')

In [9]:
df.shape

(5901, 21)

In [10]:
df["Returned"] = df["Returns"].fillna(0)

In [11]:
df["Returned"].value_counts()

Returned
0.0    5614
1.0     287
Name: count, dtype: int64

In [12]:
df[["Returns", "Returned"]].head(10)

   Returns  Returned
0      NaN       0.0
1      NaN       0.0
2      NaN       0.0
3      NaN       0.0
4      NaN       0.0
5      NaN       0.0
6      NaN       0.0
7      NaN       0.0
8      NaN       0.0
9      NaN       0.0

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.columns

Index(['Row ID+O6G3A1:R6', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales', 'Quantity', 'Profit', 'Returns', 'Payment Mode', 'Returned'],
      dtype='str')

In [15]:
df.rename(columns={"Row ID+O6G3A1:R6": "Row_ID"}, inplace=True)

In [16]:
df.columns

Index(['Row_ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales', 'Quantity', 'Profit', 'Returns', 'Payment Mode', 'Returned'],
      dtype='str')

In [17]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

In [18]:
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'region', 'product_id', 'category', 'sub_category', 'product_name',
       'sales', 'quantity', 'profit', 'returns', 'payment_mode', 'returned'],
      dtype='str')

In [19]:
df[["order_date", "ship_date"]].dtypes

order_date    str
ship_date     str
dtype: object

In [21]:
df["order_date"] = pd.to_datetime(df["order_date"], dayfirst=True)
df["ship_date"] = pd.to_datetime(df["ship_date"], dayfirst=True)

In [22]:
df[["order_date", "ship_date"]].dtypes

order_date    datetime64[us]
ship_date     datetime64[us]
dtype: object

In [23]:
df[["order_date", "ship_date"]].head()

  order_date  ship_date
0 2019-01-01 2019-01-07
1 2019-01-02 2019-01-07
2 2019-01-02 2019-01-07
3 2019-01-03 2019-01-05
4 2019-01-03 2019-01-08

In [24]:
df["shipping_days"] = (
    df["ship_date"] - df["order_date"]
).dt.days

In [26]:
df[["order_date", "ship_date", "shipping_days"]].head()

  order_date  ship_date  shipping_days
0 2019-01-01 2019-01-07              6
1 2019-01-02 2019-01-07              5
2 2019-01-02 2019-01-07              5
3 2019-01-03 2019-01-05              2
4 2019-01-03 2019-01-08              5

In [27]:
df["shipping_days"].describe()

count    5901.000000
mean        3.926962
std         1.792050
min         0.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         8.000000
Name: shipping_days, dtype: float64

In [28]:
df[["sales", "quantity", "profit"]].describe()

             sales     quantity       profit
count  5901.000000  5901.000000  5901.000000
mean    265.345589     3.781901    29.700408
std     474.260645     2.212917   259.589138
min       0.836000     1.000000 -6599.978000
25%      71.976000     2.000000     1.795500
50%     128.648000     3.000000     8.502500
75%     265.170000     5.000000    28.615000
max    9099.930000    14.000000  8399.976000

In [29]:
df[df["profit"] == df["profit"].min()]

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,category,sub_category,product_name,sales,quantity,profit,returns,payment_mode,returned,shipping_days
2184,7773,CA-2019-108196,2019-11-25,2019-12-02,Standard Class,CS-12505,Cindy Stewart,Consumer,United States,Lancaster,...,Technology,Machines,Cubify CubeX 3D Printer Double Head Print,4499.985,5,-6599.978,NaN,Cards,0.0,7

In [30]:
df[df["profit"] == df["profit"].max()]

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,category,sub_category,product_name,sales,quantity,profit,returns,payment_mode,returned,shipping_days
1681,6827,CA-2019-118689,2019-10-02,2019-10-09,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,499.95,5,8399.976,NaN,Cards,0.0,7

### Profit Validation

The `profit` column contains both positive and negative values.
Negative profit represents transactions where the business incurred a loss
and is therefore considered valid business information.

Extreme minimum and maximum profit values were inspected and found to
correspond to actual product transactions. Therefore, these values were
retained rather than removed.

In [31]:
df["ship_mode"].value_counts()

ship_mode
Standard Class    3451
Second Class      1147
First Class        959
Same Day           344
Name: count, dtype: int64

In [32]:
df["segment"].value_counts()

segment
Consumer       2997
Corporate      1774
Home Office    1130
Name: count, dtype: int64

In [33]:
df["category"].value_counts()

category
Office Supplies    3569
Furniture          1249
Technology         1083
Name: count, dtype: int64

In [34]:
df["sub_category"].value_counts()

sub_category
Binders        915
Paper          825
Furnishings    573
Phones         519
Storage        498
Art            465
Accessories    461
Chairs         355
Appliances     279
Labels         211
Tables         190
Envelopes      133
Bookcases      131
Fasteners      124
Supplies       119
Machines        65
Copiers         38
Name: count, dtype: int64

In [35]:
df["region"].value_counts()

region
West       1901
East       1688
Central    1381
South       931
Name: count, dtype: int64

In [36]:
df["payment_mode"].value_counts()

payment_mode
COD       2453
Online    2164
Cards     1284
Name: count, dtype: int64

In [37]:
df["returns"].value_counts(dropna=False)

returns
NaN    5614
1.0     287
Name: count, dtype: int64

In [38]:
df = df.drop(columns=["returns"])

In [39]:
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'region', 'product_id', 'category', 'sub_category', 'product_name',
       'sales', 'quantity', 'profit', 'payment_mode', 'returned',
       'shipping_days'],
      dtype='str')

In [42]:
df.isnull().sum()

row_id           0
order_id         0
order_date       0
ship_date        0
ship_mode        0
customer_id      0
customer_name    0
segment          0
country          0
city             0
state            0
region           0
product_id       0
category         0
sub_category     0
product_name     0
sales            0
quantity         0
profit           0
payment_mode     0
returned         0
shipping_days    0
dtype: int64

In [43]:
df.shape

(5901, 22)

In [44]:
df.dtypes

row_id                    int64
order_id                    str
order_date       datetime64[us]
ship_date        datetime64[us]
ship_mode                   str
customer_id                 str
customer_name               str
segment                     str
country                     str
city                        str
state                       str
region                      str
product_id                  str
category                    str
sub_category                str
product_name                str
sales                   float64
quantity                  int64
profit                  float64
payment_mode                str
returned                float64
shipping_days             int64
dtype: object

In [46]:
df.to_csv("data/SampleSuperstore_Cleaned.csv", index=False)

In [47]:
import os
os.path.exists("data/SampleSuperstore_Cleaned.csv")

True